In [866]:
2*4

8

In [867]:
#variable assignments
x=50

In [868]:
type(x)

int

In [869]:
help(type)

Help on class type in module builtins:

class type(object)
 |  type(object_or_name, bases, dict)
 |  type(object) -> the object's type
 |  type(name, bases, dict) -> a new type
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __dir__(self, /)
 |      Specialized __dir__ implementation for types.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __instancecheck__(self, instance, /)
 |      Check if an object is an instance.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __setattr__(self, name, value, /)
 |      Implement setattr(self, name, value).
 |  
 |  __sizeof__(self, /)
 |      Return memory consumption of the type object.
 |  
 |  __subclasscheck__(self, subclass, /)
 |     

In [870]:
print(x)

50


In [871]:
x

50

In [872]:
y=50

In [873]:
id(y)

4323912640

In [874]:
id(x)

#It has same memory location. if the value is in small size variable points to the same object if the value is same

4323912640

In [875]:
#data structures
#list : MUtable collection of data (single dimension). Can be of any data
list1 = [2,12,532,534]


In [876]:
list2=["mumbai",23]

In [877]:
type(list1)

list

In [878]:
list1

[2, 12, 532, 534]

In [879]:
list1
list2

['mumbai', 23]

In [880]:
print("this is my list",list1)
print(list2)

this is my list [2, 12, 532, 534]
['mumbai', 23]


In [881]:
list1[2:4]

[532, 534]

In [882]:
list1[2:-1]

[532]

In [883]:
list1[1:-1]

[12, 532]

In [884]:
list1[1:-0]

[]

In [885]:
list1[1:0]

[]

In [886]:
list1[0:-1]

[2, 12, 532]

In [887]:
list1[0:-2]

[2, 12]

In [888]:
list1.insert(2,"India")

In [889]:
list1

[2, 12, 'India', 532, 534]

In [890]:
list1[0]="213"

In [891]:
list1

['213', 12, 'India', 532, 534]

In [892]:
#data structure : Tuple
#it is same as list, but tuple is mutable

t1=(212,6545,545)
t2=tuple(list2)

In [893]:
print(t2)

('mumbai', 23)


In [894]:
#dictionary
dict1={'Id':50,"Name":"Namrata", "name": "Yogesh"}

In [895]:
dict1

{'Id': 50, 'Name': 'Namrata', 'name': 'Yogesh'}

In [896]:
dict1['name']

'Yogesh'

In [897]:
dict1.keys()

dict_keys(['Id', 'Name', 'name'])

In [898]:
dict1.update({'Id':100})

In [899]:
dict1

{'Id': 100, 'Name': 'Namrata', 'name': 'Yogesh'}

In [900]:
#Set
#ordered collection of unique elements

s1 = {85,85,65}

In [901]:
s1

{65, 85}

In [902]:
s1 = {85,25}

In [903]:
s2 = {85,85,65}

In [904]:
s1 & s2

{85}

In [905]:
s1 | s2

{25, 65, 85}

In [906]:
#library : numpy

In [907]:
import numpy

In [908]:
distance_array = numpy.array([400,600,800])
time_array = numpy.array([40,60,80])

In [909]:
import numpy as np

In [910]:
distance_array/time_array

array([10., 10., 10.])

In [911]:
a2d=np.array([[1,2,3],[10,20,30]])

In [912]:
a2d

array([[ 1,  2,  3],
       [10, 20, 30]])

In [913]:
#check dimensions
a2d.ndim

2

In [914]:
#checking dimension details 
#how many columns rates
a2d.shape

(2, 3)

In [915]:
#checking data type
a2d.dtype

dtype('int64')

In [916]:
#indexing
a2d[1,2]

30

In [917]:
a2d[0:,1]

array([ 2, 20])

In [918]:
a2d[0:,1:]

array([[ 2,  3],
       [20, 30]])

In [919]:
import pandas as p

In [920]:
s1 = p.Series(['india',1,1.43])

In [921]:
s1

0    india
1        1
2     1.43
dtype: object

In [922]:
s2 = p.Series(['india',1,1.43], index=['a','b','c'])

In [923]:
s2

a    india
b        1
c     1.43
dtype: object

In [924]:
s2[1]

1

In [925]:
s2.a

'india'

In [926]:
s3 = p.Series(['indi',10,143], index=['b','c','a'])

In [927]:
s4 = p.Series([1,2,3], index=['b','c','a'])

In [928]:
s5 = p.Series([4,5,6], index=['a','b','c'])

In [929]:
s4+s5

a    7
b    6
c    8
dtype: int64

In [930]:
s6 = p.Series([4,5,6,7], index=['a','b','c','d'])

In [931]:
s4+s6

a    7.0
b    6.0
c    8.0
d    NaN
dtype: float64

In [ ]:
s3.add(s2,fill_value = O)